### ISSUE TITLE
[Feature Request] Add icon into template

### ISSUE THREAD

**Issue by anno0** [dakhnod/OctoPrint-TabInfo#1]
Is it possible to extend the templates with OctoPrint Icon?

I appended the view of OctoPi tab in Mozilla Firefox.

![tab](https://github.com/dakhnod/OctoPrint-TabInfo/assets/2607705/5c9869f4-25f3-47cd-bdc6-02b0d02cba20)

**Comment by dakhnod** [comment]
It should display the OctoPrint icon...
I have no influence on that 

Can you load the favicon? Or is there an error?

**Comment by anno0** [comment]
OK, I restarted the system. The icon is shown again.
